### PR TITLE
Several small grammatical corrections

### PR DESCRIPTION
**Pull request by chirinosky**
Thank you so much for writing and sharing your book. Your rentomatic blog post was one of my first resources for applying clean architecture to Python when I first learned about it. I'm very excited and thankful for your contributions!

### CODE REVIEW

**Comment by chirinosky** [comment]
Updated Chapter 02 - Basic Example

**Comment by lgiordani** [comment]
Thanks a lot! I'm going to review and apply theme as soon as possible. Glad that you enjoyed it and thanks for your help.

**Comment by chirinosky** [comment]
Including chapter 03.

**Comment by lgiordani** [comment]
Hi @chirinosky! Thanks for the great work. I'm about to merge the PR, but I wanted to check if you think you have more corrections to make. Thanks!

**Comment by chirinosky** [comment]
Thank you. I plan on completing chapter 04 this week. If you can wait until then I'll respond to this post confirming.

**Comment by lgiordani** [comment]
I can definitely wait, no hurries!

**Comment by chirinosky** [comment]
Hi, I've added the rest of the changes. Thanks again for the wonderful book!

**Comment by lgiordani** [comment]
I will shortly publish a new version of the book with your corrections. Thanks again!

**Pull request merged**
